exemple_mvc/exemple_mvc/Models/Produit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exemple_mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;

    public partial class produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produit()
        {
            this.Details_Command = new HashSet<Details_Command>();
        }

        public int ID_PR { get; set; }
        public string NAME_PRODUIT { get; set; }
        public Nullable<decimal> PRIX { get; set; }
        public string DESCRIPTION_PR { get; set; }
        public string IMAGE { get; set; }
        public string TYPE_PRODUIT { get; set; }

        SqlCommand cmd;
        SqlDataAdapter da;
        DataSet ds;
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_Command> Details_Command { get; set; }
        /// <summary>
        /// 0
        /// </summary>
        /// <returns></returns>

    }
}

exemple_mvc/exemple_mvc/Controllers/produitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using exemple_mvc.Models;

namespace exemple_mvc.Controllers
{
    public class produitsController : Controller
    {
        private DB_ASP_ProjetEntities2 db = new DB_ASP_ProjetEntities2();
        produit pr = new produit();
        // GET: produits
        public ActionResult Index()
        {
            return View(db.produit.ToList());
        }


        // GET: produits
        public ActionResult Show(string Search)
        {
            if (Search == null)
            {
                return View(db.produit);
            }
            else
            {
                return View(db.produit.Where(x => x.NAME_PRODUIT.Contains(Search)));
            }
                
            
        }
        // GET: ordinateur
        public ActionResult ordinateur(string Search)
        {
            if (Search == null)
            {
                return View(db.produit);
            }
            else
            {
                return View(db.produit.Where(x => x.NAME_PRODUIT.Contains(Search)));
            }

        }
        // GET: produits
        public ActionResult mobile(string Search)
        {
            if (Search == null)
            {
                return View(db.produit);
            }
            else
            {
                return View(db.produit.Where(x => x.NAME_PRODUIT.Contains(Search)));
            }

        }
        // GET: produits
        public ActionResult system(string Search)
        {
            if (Search == null)
            {
                return View(db.produit);
            }
            else
            {
                return View(db.produit.Where(x => x.NAME_PRODUIT.Contains(Search)));
            }
               
        }

        // GET: produits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            produit produit = db.produit.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }
        public ActionResult ArticleInfo(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            produit produit = db.produit.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // GET: produits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: produits/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NAME_PRODUIT,PRIX,DESCRIPTION,IMAGE")] produit produit)
        {
            if (ModelState.IsValid)
            {
                db.produit.Add(produit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produit);
        }

        // GET: produits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            produit produit = db.produit.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: produits/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NAME_PRODUIT,PRIX,DESCRIPTION,IMAGE")] produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(produit);
        }

        // GET: produits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            produit produit = db.produit.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            produit produit = db.produit.Find(id);
            db.produit.Remove(produit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

exemple_mvc/exemple_mvc/Views/produits/ArticleInfo.cshtml
@model exemple_mvc.Models.produit

@{
    ViewBag.Title = "Article | "+Model.NAME_PRODUIT;
    Layout = "~/Views/Shared/_LayoutGlobal.cshtml";
}

<div class="container" id="shop">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <!-- Custom styles for this template -->

    <div class="row">

        <div class="col-lg-3">
            <h1 class="my-4">@Model.NAME_PRODUIT </h1>
            <div class="list-group">
                <a href="http://localhost:52825/produits/mobile" class="list-group-item">Mobile</a>
                <a href="http://localhost:52825/produits/ordinateur" class="list-group-item">Ordinateur</a>
                <a href="http://localhost:52825/produits/system" class="list-group-item">Systéme De Surveillance</a>
                <a href="http://localhost:52825/produits/Show" class="list-group-item">Afficher tout</a>
            </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div class="card mt-4">
                <img class="card-img-top img-fluid" src="~/img/portfolio/@Model.IMAGE">
                <div class="card-body">
                    <h3 class="card-title">@Model.NAME_PRODUIT</h3>
                    <h4>@Model.PRIX DH</h4>
                    <p class="card-text">@Model.DESCRIPTION_PR</p>

                    <label for="qty">Quantité :</label>
                    <input type="number" id="qty" name="qty" min="1" max="20" value="1" style="margin-right:60px;">
                    <a href="#" class="btn btn-success">ACHETER</a> <a href="@Url.Action("Add", "AddToCart", new { produit = Model,Id=Model.ID_PR }))" class="btn btn-success"><i class="fas fa-cart-plus"></i></a>
                </div>
            </div>
            <!-- /.card -->

            <!-- /.col-lg-9 -->

        </div>

    </div>
</div>
<!-- /.container -->

exemple_mvc/exemple_mvc/Views/produits/Create.cshtml
@model exemple_mvc.Models.produit

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutGlobal.cshtml";
}

<h2>Create</h2>
<div id="conteneur">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>produit</h4>
            
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.NAME_PRODUIT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NAME_PRODUIT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NAME_PRODUIT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PRIX, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PRIX, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PRIX, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DESCRIPTION_PR, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DESCRIPTION_PR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DESCRIPTION_PR, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IMAGE, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IMAGE, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TYPE_PRODUIT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TYPE_PRODUIT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TYPE_PRODUIT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </div>

exemple_mvc/exemple_mvc/Views/produits/Show.cshtml
@model IEnumerable<exemple_mvc.Models.produit>

@{
    ViewBag.Title = "Nos Produits";
    Layout = "~/Views/Shared/_LayoutGlobal.cshtml";
}

<div class="container">

    <div class="row" id="shop">

        <div class="col-lg-3" id="page-top">

            <h1 class="my-4">Notre Magazin</h1>
            <div class="list-group">
                
                    @using (Html.BeginForm("Show", "produits", FormMethod.Get, new { @class = "list-group" }))
                    {
                        <input type="text" name="Search" placeholder="Tapez Votre Produit à chercher"> <input type="submit" value="Chercher" /><br />
                    }
                
                <a href="http://localhost:52825/produits/mobile" class="list-group-item">Mobiles</a>
                <a href="http://localhost:52825/produits/ordinateur" class="list-group-item">Ordinateurs</a>
                <a href="http://localhost:52825/produits/system" class="list-group-item">Systémes De Surveillance</a>
                <a href="http://localhost:52825/produits/Show" class="list-group-item">Afficher tout</a>
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="~/img/portfolio/100.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/img/portfolio/102.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/img/portfolio/103.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                @foreach (var item in Model)
                {

                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="http://localhost:52825/produits/ArticleInfo/@item.ID_PR"><img class="card-img-top" src="~/img/portfolio/@Html.DisplayFor(modelItem => item.IMAGE)"></a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a>@Html.ActionLink(item.NAME_PRODUIT, "ArticleInfo", new { id = item.ID_PR })</a>
                                </h4>
                                <h5> @Html.DisplayFor(modelItem => item.PRIX) DH</h5>

                                <p class="card-text">@Html.DisplayFor(modelItem => item.DESCRIPTION_PR)</p>
                            </div>
                            <div class="card-footer">
                                @switch (item.TYPE_PRODUIT)
                                {
                                    case "ordinateur":
                                        <small class="text-muted" style="font-weight:bold;">Catégorie : Ordinateur</small>
                                        break;
                                    case "mobile":
                                        <small class="text-muted" style="font-weight:bold;">Catégorie : Téléphone</small>
                                        break;
                                    case "system":
                                        <small class="text-muted" style="font-weight:bold;">Catégorie : Systéme De Surveillance</small>
                                        break;
                                    default:
                                        <small class="text-muted" style="font-weight:bold;"></small>
                                        break;
                                }

                            </div>
                        </div>
                    </div>

                }
                @if (Model.Count() == 0)
                {
                    <h1>Produit Introuvable</h1>
                }
            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>

exemple_mvc/exemple_mvc/Views/produits/mobile.cshtml
@model IEnumerable<exemple_mvc.Models.produit>

@{
    ViewBag.Title = "Nos Téléphones";
    Layout = "~/Views/Shared/_LayoutGlobal.cshtml";
}

<div class="container">


    <div class="row" id="shop">

        <div class="col-lg-3" id="page-top">

            <h1 class="my-4">Notre Magazin</h1>
            <div class="list-group">
                @using (Html.BeginForm("Show", "produits", FormMethod.Get, new { @class = "list-group" }))
                {
                    <input type="text" name="Search" placeholder="Tapez Votre Produit à chercher"> <input type="submit" value="Chercher" /><br />
                }
                <a href="http://localhost:52825/produits/mobile" class="list-group-item">Mobiles</a>
                <a href="http://localhost:52825/produits/ordinateur" class="list-group-item">Ordinateurs</a>
                <a href="http://localhost:52825/produits/system" class="list-group-item">Systémes De Surveillance</a>
                <a href="http://localhost:52825/produits/Show" class="list-group-item">Afficher tout</a>
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="~/img/portfolio/100.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/img/portfolio/102.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/img/portfolio/103.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                @foreach (var item in Model)
                {
                    if (item.TYPE_PRODUIT == "mobile")
                    {
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="http://localhost:52825/produits/ArticleInfo/@item.ID_PR"><img class="card-img-top" src="~/img/portfolio/@Html.DisplayFor(modelItem => item.IMAGE)"></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a>@Html.ActionLink(item.NAME_PRODUIT, "ArticleInfo", new { id = item.ID_PR })</a>
                                    </h4>
                                    <h5> @Html.DisplayFor(modelItem => item.PRIX) DH</h5>
                                    <p class="card-text">@Html.DisplayFor(modelItem => item.DESCRIPTION_PR)</p>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted" style="font-weight:bold;">Catégorie : Téléphone</small>
                                </div>
                            </div>
                        </div>
                    }

                }
                @if (Model.Count() == 0)
                {
                    <h1>Produit Introuvable</h1>
                }
            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>

exemple_mvc/exemple_mvc/Views/produits/ordinateur.cshtml
@model IEnumerable<exemple_mvc.Models.produit>

@{
    ViewBag.Title = "Nos Ordinateurs";
    Layout = "~/Views/Shared/_LayoutGlobal.cshtml";
}

<div class="container">

    <div class="row" id="shop">

        <div class="col-lg-3" id="page-top">

            <h1 class="my-4">Notre Magazin</h1>
            <div class="list-group">
                @using (Html.BeginForm("Show", "produits", FormMethod.Get, new { @class = "list-group" }))
                {
                    <input type="text" name="Search" placeholder="Tapez Votre Produit à chercher"> <input type="submit" value="Chercher" /><br />
                }
                <a href="http://localhost:52825/produits/mobile" class="list-group-item">Mobiles</a>
                <a href="http://localhost:52825/produits/ordinateur" class="list-group-item">Ordinateurs</a>
                <a href="http://localhost:52825/produits/system" class="list-group-item">Systémes De Surveillance</a>
                <a href="http://localhost:52825/produits/Show" class="list-group-item">Afficher tout</a>
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="~/img/portfolio/100.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/img/portfolio/102.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/img/portfolio/103.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                @foreach (var item in Model)
                {
                    if (item.TYPE_PRODUIT == "ordinateur")
                    {
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="http://localhost:52825/produits/ArticleInfo/@item.ID_PR"><img class="card-img-top" src="~/img/portfolio/@Html.DisplayFor(modelItem => item.IMAGE)"></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a>@Html.ActionLink(item.NAME_PRODUIT, "ArticleInfo", new { id = item.ID_PR })</a>
                                    </h4>
                                    <h5> @Html.DisplayFor(modelItem => item.PRIX) DH</h5>
                                    <p class="card-text">@Html.DisplayFor(modelItem => item.DESCRIPTION_PR)</p>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted" style="font-weight:bold;">Catégorie : Ordinateur</small>
                                </div>
                            </div>
                        </div>
                    }

                }
                @if (Model.Count() == 0)
                {
                    <h1>Produit Introuvable</h1>
                }
            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>

exemple_mvc/exemple_mvc/Views/produits/system.cshtml
@model IEnumerable<exemple_mvc.Models.produit>

@{
    ViewBag.Title = "Nos systémes de surveillance";
    Layout = "~/Views/Shared/_LayoutGlobal.cshtml";
}

<div class="container">

    <div class="row" id="shop">

        <div class="col-lg-3" id="page-top">

            <h1 class="my-4">Notre Magazin</h1>
            <div class="list-group">
                @using (Html.BeginForm("Show", "produits", FormMethod.Get, new { @class = "list-group" }))
                {
                    <input type="text" name="Search" placeholder="Tapez Votre Produit à chercher"> <input type="submit" value="Chercher" /><br />
                }
                <a href="http://localhost:52825/produits/mobile" class="list-group-item">Mobiles</a>
                <a href="http://localhost:52825/produits/ordinateur" class="list-group-item">Ordinateurs</a>
                <a href="http://localhost:52825/produits/system" class="list-group-item">Systémes De Surveillance</a>
                <a href="http://localhost:52825/produits/Show" class="list-group-item">Afficher tout</a>
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="~/img/portfolio/100.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/img/portfolio/102.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="~/img/portfolio/103.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                @foreach (var item in Model)
                {
                    if (item.TYPE_PRODUIT == "system")
                    {
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="http://localhost:52825/produits/ArticleInfo/@item.ID_PR"><img class="card-img-top" src="~/img/portfolio/@Html.DisplayFor(modelItem => item.IMAGE)"></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a>@Html.ActionLink(item.NAME_PRODUIT, "ArticleInfo", new { id = item.ID_PR })</a>
                                    </h4>
                                    <h5> @Html.DisplayFor(modelItem => item.PRIX) DH</h5>
                                    <p class="card-text">@Html.DisplayFor(modelItem => item.DESCRIPTION_PR)</p>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted" style="font-weight:bold;">Catégorie : Systéme De Surveillance</small>
                                </div>
                            </div>
                        </div>
                    }

                }
                @if(Model.Count() == 0)
                {
                    <h1>Produit Introuvable</h1>
                }
            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>